# Generated by Django 4.2.16 on 2026-05-20 21:40

from django.db import migrations, models
import pgvector.django.vector
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.RunSQL("CREATE EXTENSION IF NOT EXISTS vector;", reverse_sql=migrations.RunSQL.noop),
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('analysis_type', models.CharField(choices=[('local', 'Análise Local'), ('local_context', 'Análise Local com Contexto'), ('general_context', 'Análise Geral com Contexto'), ('total', 'Análise Total'), ('reader_simulation', 'Simulação de Leitores'), ('creative_suggestion', 'Sugestão Criativa')], max_length=25)),
                ('reader_profiles', models.JSONField(blank=True, default=list)),
                ('content', models.TextField()),
                ('credits_consumed', models.PositiveIntegerField(default=1)),
                ('ai_model', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Análise',
                'verbose_name_plural': 'Análises',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContextVector',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text_excerpt', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(dimensions=384)),
                ('indexed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Vetor de Contexto',
                'verbose_name_plural': 'Vetores de Contexto',
            },
        ),
    ]
