# Generated by Django 4.2.16 on 2026-05-20 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('analyses', '0002_initial'),
        ('chapters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contextvector',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vectors', to='projects.project'),
        ),
        migrations.AddField(
            model_name='analysis',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analyses', to='chapters.chapter'),
        ),
        migrations.AddField(
            model_name='analysis',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='projects.project'),
        ),
    ]
