# Generated by Django 4.2.16 on 2026-07-02 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyses', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='analysis_type',
            field=models.CharField(choices=[('local', 'Análise Local'), ('local_context', 'Análise Local com Contexto'), ('general_context', 'Análise Geral com Contexto'), ('total', 'Análise Total'), ('reader_simulation', 'Simulação de Leitores'), ('creative_suggestion', 'Sugestão Criativa'), ('book_general', 'Análise Geral do Livro'), ('book_total', 'Análise Total do Livro'), ('book_reader_simulation', 'Simulação de Leitores — Livro')], max_length=25),
        ),
    ]
