# Generated by Django 4.2.16 on 2026-05-20 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('chapters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='projects.project'),
        ),
        migrations.AlterUniqueTogether(
            name='chapter',
            unique_together={('project', 'number')},
        ),
    ]
